Added password hash functionality
software-students-fall2021/project-setup-sneaky-seven pull request #143
Opened 2021-12-01 20:34 UTC by sdl433

This version of the code, as promised (no pun intended), hashes the password and stores the hash into the database. Please check and approve, it works perfectly afaik.

2021-12-01 21:56 UTC, Jennifercheukyin requested changes
Thanks for doing the password encryption! Please review my suggestions. 
After you are done with the changes, please test it end-to-end to see if the password stored in the database is actually encrypted. thank you

2021-12-01 21:56 UTC, Jennifercheukyin commented on back-end/app.js
> +    const hash = await bcrypt.hash(password, 10)
Please name it as `encrypted_password` to make the code more readable.

2021-12-01 21:56 UTC, Jennifercheukyin commented on back-end/app.js
> +      hash,
Did you test it end-to-end? I doubt this will successfully create a user. In the schema, we only have `password `field. What you probably need to do is `password: encrypted_password`

2021-12-01 21:56 UTC, Jennifercheukyin commented on back-end/app.js
> +    if (comparison) {
Suggestion: 
`if (user && (await bcrypt.compare(password, user.password)))`

there is no field named hash in our schema :)

2021-12-01 22:58 UTC, sdl433 commented on back-end/app.js
> +    const hash = await bcrypt.hash(password, 10)
I made another commit where I renamed `hash` to `hashedPassword`

2021-12-01 22:59 UTC, sdl433 commented on back-end/app.js
> +      hash,
I changed model/user.js so that the `password` field is now a `hashedPassword` field

2021-12-01 23:01 UTC, sdl433 commented on back-end/app.js
> +    if (comparison) {
I just changed `user.hash` to `user.hashedPassword`

2021-12-01 23:01 UTC, sdl433 commented
I just implemented the suggested changes, please let me know if anything else is needed.

2021-12-01 23:29 UTC, Jennifercheukyin requested changes

2021-12-01 23:29 UTC, Jennifercheukyin commented on back-end/model/user.js
> +    hashedPassword: { type: String },
I'd suggest we don't touch the definition of userSchema since it's shared across. Please leave the field `password` as it is.

2021-12-01 23:29 UTC, Jennifercheukyin commented on back-end/app.js
> +      hashedPassword,
Here, please refer back to the suggestion I made earlier. Change it this way:
`password: hashedPassword`

2021-12-02 00:09 UTC, sdl433 commented on back-end/model/user.js
> +    hashedPassword: { type: String },
Ok, I just reverted the changes in `userSchema`

2021-12-02 00:09 UTC, sdl433 commented on back-end/app.js
> +      hashedPassword,
I implemented this change in my current commit

2021-12-02 00:10 UTC, sdl433 commented
Alright, I just implemented the suggestions. Please take a look and let me know if there's anything else that's necessary.

2021-12-02 00:51 UTC, Jennifercheukyin approved these changes

2021-12-02 16:21 UTC, merged