Seb adjustable accounts for stats
software-students-fall2021/project-setup-sneaky-seven pull request #170
Opened 2021-12-06 01:50 UTC by sdl433

This PR gives the user the functionality to choose the accounts for which they can view stats. I also implemented much needed design changes, as well as refactored some code to make things more organized. Please review, let me know your thoughts, as well as if anything is neede
![Screenshot 2021-12-05 203930](https://user-images.githubusercontent.com/59803959/144774711-57e44448-eafb-43cf-8bd2-e8f51ea1b1f2.png)
![Screenshot 2021-12-05 204641](https://user-images.githubusercontent.com/59803959/144774741-8f6377e3-dbe6-4be2-a01b-f7887055e621.png)

d
![Screenshot 2021-12-05 204021](https://user-images.githubusercontent.com/59803959/144774721-c743f21f-794e-4cb9-b67f-af8c9f58fef4.png)
![Screenshot 2021-12-05 204108](https://user-images.githubusercontent.com/59803959/144774729-1e185320-1db7-42f8-9807-a4fa05f9201f.png)

.

2021-12-06 03:24 UTC, azc242 requested changes
The changes look great (love the transparent background on the charts)! 
Just a few comments/changes for best practices (not using `let` and not using magic numbers for `px`).

2021-12-06 03:24 UTC, azc242 commented on front-end/src/components/Statistics/utils/prepare_stats.js
> +  let spendingTrend = [];
Can we turn all the `let` into something more robust? I don't think we're supposed to use `let`.

2021-12-06 03:24 UTC, azc242 commented on front-end/src/components/css/StatsNavbar.css
> +  padding: 14px 16px;
nit: can you try to use dynamic units? I'm worried this might break on mobile or different sized screens

2021-12-06 03:24 UTC, azc242 commented on front-end/src/components/Statistics/Charts/PieChart.js
> +        backgroundColor: { fill: 'transparent' }
I really like this, it looks super slick!

2021-12-06 03:24 UTC, azc242 commented on front-end/src/components/css/Timebar.css
> +  padding: 14px 16px;
same as above, try not to use fixed sizes for responsiveness

2021-12-06 03:50 UTC, sdl433 commented
Hey, I took a look at the suggested changes and implemented them. Please take a look and review again, and please suggest any other modifications that come to mind.

2021-12-06 03:57 UTC, sdl433 commented on front-end/src/components/Statistics/utils/prepare_stats.js
> +  let spendingTrend = [];
I changed all the `let`s in `prepare_stats.js` into `consts`, except for `balance`

2021-12-06 03:58 UTC, sdl433 commented on front-end/src/components/css/StatsNavbar.css
> +  padding: 14px 16px;
I just changed those constants into percentages.

2021-12-06 03:59 UTC, sdl433 commented on front-end/src/components/Statistics/Charts/PieChart.js
> +        backgroundColor: { fill: 'transparent' }
Thanks, I think so too!

2021-12-06 03:59 UTC, sdl433 commented on front-end/src/components/css/Timebar.css
> +  padding: 14px 16px;
Already fixed this issue using percents as well.

2021-12-08 22:59 UTC, tangym27 reviewed
this looks really beautiful! nice job woo 

three minor things:
1 - if i dont spend anything (#broke life) this is what the chart looks like:
<img width="200" alt="Screen Shot 2021-12-08 at 5 25 37 PM" src="https://user-images.githubusercontent.com/34128141/145299066-45638d7e-5bed-4c56-bd2c-50579e411de9.png">
is this intended?

2 - (style)
<img width="200" alt="Screen Shot 2021-12-08 at 5 35 52 PM" src="https://user-images.githubusercontent.com/34128141/145302334-99f76dbc-1d7b-4cfa-bd5e-dcf0af08967f.png">
i think it might look better if you switched the positions of the navbars. balance and spending seems 'higher' than the date features. as the balance and spending are the tabs themselves and that bar covers the whole screen so it makes sense for it to be close to the top. then the navbar that sorts by date should be a subsection of that (it has a caption of `The following charts` so it feels weird that immediately following is a navbar). Also looking at the date thing makes me notice all the negative space of the original navbar so it might be nice to shorten it.

tldr: i think this looks a bit nicer but wanna hear your thoughts
![image](https://user-images.githubusercontent.com/34128141/145303822-aafb16e9-8d57-4290-8c0a-f7ca8ac0af9a.png)

3- stats kinda take a long time to load for me. should i be doing something to make it faster?

2021-12-09 23:00 UTC, sdl433 commented
I made a commit just now.

Addressing 1: The Spending page should now show that there is "No Spending Data Available", please confirm that that is indeed the case.

Addressing 2: I implemented your suggestion

Addressing 3: Ah yes, stats currently takes a bit of a long time, especially if we're loading data from the last year. There's nothing the user could do to make it faster.

2021-12-09 23:54 UTC, tangym27 reviewed
Left five commit suggestions.

First one was towards the removal of db secrets
Other four was so that the stat navbar was centered to look like this:
![image](https://user-images.githubusercontent.com/34128141/145493864-ddb2e4c2-2e12-43fc-863c-ebae91b08005.png)

If you prefer the other way and want them aligned to the left, feel free to reject the suggestions (centering looks nice to me but I will trust your judgement).

Either way, once you resolve these commits, lmk and I'll approve.

2021-12-09 23:54 UTC, tangym27 commented on front-end/src/components/css/StatsNavbar.css
> +}
```suggestion
justify-content: center;
}
```

2021-12-09 23:54 UTC, tangym27 commented on front-end/src/components/css/StatsNavbar.css
>  }
```suggestion
justify-content: center;
}
```

2021-12-09 23:54 UTC, tangym27 commented on front-end/src/components/css/Timebar.css
> +}
```suggestion
justify-content: center;
}
```

2021-12-09 23:54 UTC, tangym27 commented on front-end/src/components/css/Timebar.css
> +}
```suggestion
justify-content: center;
}
```

2021-12-09 23:54 UTC, tangym27 commented on back-end/app.js
> +
```suggestion
```

I assume you want to remove it?

2021-12-10 00:22 UTC, sdl433 commented
Haha sorry about revealing the db secret, I keep on forgetting to remove it. As for the other suggestions, I just added them. Please let me know if anything else is needed.

2021-12-10 00:54 UTC, tangym27 approved these changes
Thanks for changing! I don't have multiple accounts to test it on but I assume you tested it too.

Stats look great :D!

2021-12-10 01:35 UTC, merged