Connect to MongoDB Atlas
software-students-fall2021/project-setup-sneaky-seven pull request #86
Opened 2021-11-11 21:23 UTC by Jennifercheukyin

1. Configure MongoDB Atlas, set up backend to connect to the database 
2. Provided an example function on how to post to database from backend

The example function is to post `access_token_object` to the database. After posting, we can see the entry in the database. 
![Screen Shot 2021-11-11 at 4 19 46 PM](https://user-images.githubusercontent.com/49820142/141370905-34acdcf9-0e07-40f4-a0d0-74280ec7fbdf.png)

2021-11-12 09:25 UTC, tangym27 requested changes
Thanks for connecting the backend to mongodb :) . Could you also give us the login info for the mongodb atlas? I assume the team will want to have access to it to see the documents  and info while developing.

Do have a few things that need to be fixed before merging (per project requirements and practices)– let me know your thoughts and nice job!

2021-11-12 09:25 UTC, tangym27 commented on back-end/app.js
> +  const AccessToken = mongoose.model('AccessToken', accessTokenSchema);
This shouldn't be done per-request. This line creates a new collection in MongoDb (probably with the same name as well? Not sure what would happen there). Additionally, querying access tokens under this model likely wouldn't work.

2021-11-12 09:25 UTC, tangym27 commented on back-end/app.js
> +const DB_NAME = "database"
Does these need to be separate variables? Where do they get used besides in `db_url`? Additionally, why are you using `let` for `DB_PASSWORD` instead of `const` ?

2021-11-12 09:25 UTC, tangym27 commented on back-end/app.js
> +const db_url = `mongodb+srv://sneaky-seven:${DB_PASSWORD}@cluster0.6ophh.mongodb.net/${DB_NAME}?retryWrites=true&w=majority`
This really should be a single environment variable, and not a template literal. What are your thoughts?

Additionally, the requirements state:

> Any credentials used to log into a database or other remote service must be stored in a hidden file called .env that is excluded from version control by adding it to your .gitignore file. Load these credentials from environmental variables into your project using the dotenv module.

I would remove the `sneaky-seven` username from version control.

2021-11-12 22:23 UTC, Jennifercheukyin commented on back-end/app.js
> +  const accessTokenSchema = new mongoose.Schema({
This is just an example function to test if the connection is successfull. I didn't take into consideration of the actual use cases. I'll comment out this function for now after we have finalized how to store access_token under users. 
Thanks for the feedback!

2021-11-15 15:58 UTC, merged

2021-11-15 19:17 UTC, tangym27 reviewed
Thanks for making those changes :)